"""sync current database schema

Revision ID: 16aa1d65817a
Revises: 1923a2c264f5
Create Date: 2026-09-14 23:17:34.022088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16aa1d65817a'
down_revision: Union[str, Sequence[str], None] = '1923a2c264f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    indexes = inspector.get_indexes("vehicles")
    index_names = {index["name"] for index in indexes}

    if "ix_vehicles_driver_id" not in index_names:
        op.create_index(
            "ix_vehicles_driver_id",
            "vehicles",
            ["driver_id"],
            unique=False
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_driver_id'), table_name='vehicles')
    # ### end Alembic commands ###
