"""add procurement workflow

Revision ID: 4ca20af8f718
Revises: 98b7f783b643
Create Date: 2026-09-18 16:48:26.459190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ca20af8f718'
down_revision: Union[str, Sequence[str], None] = '98b7f783b643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('mandi_id', sa.Integer(), nullable=False),
    sa.Column('crop_type', sa.String(length=100), nullable=False),
    sa.Column('booked_quantity', sa.Float(), nullable=False),
    sa.Column('weighed_quantity', sa.Float(), nullable=False),
    sa.Column('quality_grade', sa.String(length=50), nullable=False),
    sa.Column('procurement_amount', sa.Float(), nullable=False),
    sa.Column('procurement_status', sa.String(length=30), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('payment_status', sa.String(length=30), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mandi_id'], ['mandis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procurements_booking_id'), 'procurements', ['booking_id'], unique=True)
    op.create_index(op.f('ix_procurements_farmer_id'), 'procurements', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_procurements_id'), 'procurements', ['id'], unique=False)
    op.create_index(op.f('ix_procurements_mandi_id'), 'procurements', ['mandi_id'], unique=False)
    op.create_index(op.f('ix_procurements_payment_status'), 'procurements', ['payment_status'], unique=False)
    op.create_index(op.f('ix_procurements_procurement_status'), 'procurements', ['procurement_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_procurements_procurement_status'), table_name='procurements')
    op.drop_index(op.f('ix_procurements_payment_status'), table_name='procurements')
    op.drop_index(op.f('ix_procurements_mandi_id'), table_name='procurements')
    op.drop_index(op.f('ix_procurements_id'), table_name='procurements')
    op.drop_index(op.f('ix_procurements_farmer_id'), table_name='procurements')
    op.drop_index(op.f('ix_procurements_booking_id'), table_name='procurements')
    op.drop_table('procurements')
    # ### end Alembic commands ###
