"""Add login attempt tracking

Revision ID: 6b840688835f
Revises: 16aa1d65817a
Create Date: 2026-09-14 23:54:09.350242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b840688835f'
down_revision: Union[str, Sequence[str], None] = '16aa1d65817a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    # Create table only if it does not already exist
    tables = inspector.get_table_names()

    if "login_attempts" not in tables:
        op.create_table(
            "login_attempts",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("phone", sa.String(length=15), nullable=False),
            sa.Column("ip_address", sa.String(length=45), nullable=False),
            sa.Column("failed_attempts", sa.Integer(), nullable=False),
            sa.Column("last_attempt_at", sa.DateTime(), nullable=False),
            sa.Column("locked_until", sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint("id")
        )

    # Create indexes only if they do not already exist
    indexes = inspector.get_indexes("login_attempts")
    index_names = {index["name"] for index in indexes}

    if "ix_login_attempts_id" not in index_names:
        op.create_index(
            "ix_login_attempts_id",
            "login_attempts",
            ["id"],
            unique=False
        )

    if "ix_login_attempts_ip_address" not in index_names:
        op.create_index(
            "ix_login_attempts_ip_address",
            "login_attempts",
            ["ip_address"],
            unique=False
        )

    if "ix_login_attempts_phone" not in index_names:
        op.create_index(
            "ix_login_attempts_phone",
            "login_attempts",
            ["phone"],
            unique=False
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_login_attempts_phone'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_ip_address'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_id'), table_name='login_attempts')
    op.drop_table('login_attempts')
    # ### end Alembic commands ###
