"""add slots table

Revision ID: 77b9f173466f
Revises: 6b840688835f
Create Date: 2026-09-17 11:51:26.834716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77b9f173466f'
down_revision: Union[str, Sequence[str], None] = '6b840688835f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mandi_id', sa.Integer(), nullable=False),
    sa.Column('slot_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('total_slots', sa.Integer(), nullable=False),
    sa.Column('booked_slots', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mandi_id'], ['mandis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slots_id'), 'slots', ['id'], unique=False)
    op.create_index(op.f('ix_slots_is_active'), 'slots', ['is_active'], unique=False)
    op.create_index(op.f('ix_slots_mandi_id'), 'slots', ['mandi_id'], unique=False)
    op.create_index(op.f('ix_slots_slot_date'), 'slots', ['slot_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_slots_slot_date'), table_name='slots')
    op.drop_index(op.f('ix_slots_mandi_id'), table_name='slots')
    op.drop_index(op.f('ix_slots_is_active'), table_name='slots')
    op.drop_index(op.f('ix_slots_id'), table_name='slots')
    op.drop_table('slots')
    # ### end Alembic commands ###
