"""add bookings table

Revision ID: d63134c3bf31
Revises: 77b9f173466f
Create Date: 2026-09-17 11:58:34.855843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd63134c3bf31'
down_revision: Union[str, Sequence[str], None] = '77b9f173466f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_code', sa.String(length=30), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('mandi_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('crop_type', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'confirmed'"), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mandi_id'], ['mandis.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_booking_code'), 'bookings', ['booking_code'], unique=True)
    op.create_index(op.f('ix_bookings_farmer_id'), 'bookings', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.create_index(op.f('ix_bookings_mandi_id'), 'bookings', ['mandi_id'], unique=False)
    op.create_index(op.f('ix_bookings_slot_id'), 'bookings', ['slot_id'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_index(op.f('ix_bookings_vehicle_id'), 'bookings', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_vehicle_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_slot_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_mandi_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_farmer_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_booking_code'), table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ###
