"""add crop prices table

Revision ID: fd8b01580ef7
Revises: d63134c3bf31
Create Date: 2026-09-17 14:19:54.823829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd8b01580ef7'
down_revision: Union[str, Sequence[str], None] = 'd63134c3bf31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mandi_id', sa.Integer(), nullable=False),
    sa.Column('crop_name', sa.String(length=100), nullable=False),
    sa.Column('min_price', sa.Float(), nullable=False),
    sa.Column('max_price', sa.Float(), nullable=False),
    sa.Column('modal_price', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mandi_id'], ['mandis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_prices_crop_name'), 'crop_prices', ['crop_name'], unique=False)
    op.create_index(op.f('ix_crop_prices_id'), 'crop_prices', ['id'], unique=False)
    op.create_index(op.f('ix_crop_prices_mandi_id'), 'crop_prices', ['mandi_id'], unique=False)
    op.create_index(op.f('ix_crop_prices_price_date'), 'crop_prices', ['price_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crop_prices_price_date'), table_name='crop_prices')
    op.drop_index(op.f('ix_crop_prices_mandi_id'), table_name='crop_prices')
    op.drop_index(op.f('ix_crop_prices_id'), table_name='crop_prices')
    op.drop_index(op.f('ix_crop_prices_crop_name'), table_name='crop_prices')
    op.drop_table('crop_prices')
    # ### end Alembic commands ###
